name: Upload To Play Store
on:
  workflow_dispatch:

jobs:
  build-and-upload-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}
        # 中略
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Release # リリース用ビルド
        shell: bash
        run: |
          ./gradlew bundleRelease
      - name: Install python dependencies # requirements.txtから依存一括インストール
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/workflows/scripts/requirements.txt
      - name: Upload to play store # ストアの内部テストトラックへアップロード
        run: |
          python './.github/workflows/scripts/upload_aab.py' \
          # 'com.example.your.package' \
          'jp.co.githubtestproject' \
          #          'app/build/outputs/bundle/release/app-release.aab' \ # ここは環境によって変更
          'app/release/app-release.aab' \ # ここは環境によって変更
          './.github/workflows/account.json' # 必要に応じて暗号化したjsonを事前に復号化する
      成功失敗の通知